python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 256, "d_model": 32, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 256, "d_model": 32, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 512, "d_model": 512, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 168, "stride": 24, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 1, "channel_summaries": 0, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 512, "d_model": 512, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 720, "stride": 24, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 1, "channel_summaries": 0, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 512, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 1, "channel_summaries": 0, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 512, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 1, "channel_summaries": 0, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 128, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 128, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 168, "stride": 8, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 720, "stride": 8, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 512, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 4, "patience": 5, "seq_len": 168, "stride": 4, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 512, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 4, "patience": 5, "seq_len": 720, "stride": 4, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 512, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 168, "stride": 8, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 512, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 720, "stride": 8, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 64, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 168, "stride": 8, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 64, "d_model": 64, "dropout": 0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 720, "stride": 8, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 512, "dropout": 0, "e_layers": 1, "horizon": 10, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 60, "patience": 5, "seq_len": 60, "stride": 60, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 128, "d_model": 512, "dropout": 0, "e_layers": 1, "horizon": 30, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 60, "patience": 5, "seq_len": 180, "stride": 60, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 64, "d_model": 256, "dropout": 0, "e_layers": 1, "horizon": 10, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 10, "patience": 5, "seq_len": 60, "stride": 10, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/nmask2"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "nmask2.Nmask2" --model-hyper-params '{"alpha": 0, "batch_size": 64, "d_ff": 64, "d_model": 256, "dropout": 0, "e_layers": 1, "horizon": 30, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 10, "patience": 5, "seq_len": 180, "stride": 10, "pad_method": "learn", "predict_method": "future_patch", "use_t": 1, "use_t_exog": 1, "channel_attn_mode": "embedding", "channel_attn_type": "local_summary", "channel_fusion_mode": "cross_attn", "channel_window": 3, "channel_summaries": 2, "architecture": "encoder_decoder", "temporal_attn_scope": "target_only", "use_future_exog": true}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/nmask2"
